### model
model_name_or_path: /data/user/jiangkailin/data_ckpt/ckpt/llava-1.5-7b-hf
# image_max_pixels: 262144
# video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora

# use_eaft_loss: true

# use_dft_loss: true

# use_asft_loss: true
# asft_alpha: 0.1 

use_kore_loss: true
kore_alpha: 0.1
kore_beta: 1


lora_rank: 4
lora_target: all

### dataset
dataset: mllm_demo_test    # 这里是我们配置的数据集
template: llava
cutoff_len: 2048
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: /data/user/jiangkailin/data_ckpt/train_ckpt/llava-1.5-7b-hf
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0     # 训练3个ep
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
# flash_attn: auto # 自动的

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500